name: elvira
description: "Launcher acessível para idosos com suporte offline e assistente pessoal."
publish_to: "none"
version: 0.0.5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI e Acessibilidade
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.10+1

  # Local Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.9.0
  path_provider: ^2.1.2

  # TTS (Voz Offline) erro de nurget
  #flutter_tts: ^3.8.3

  # Notificações Locais
  flutter_local_notifications: ^21.0.0

  # Permissões
  permission_handler: ^12.0.0

  # Contatos reais do dispositivo
  flutter_contacts: ^1.1.9

  # Comunicação com WhatsApp (via intents) e etc
  url_launcher: ^6.2.5

  # Ligação direta sem abrir o discador nativo
  flutter_phone_direct_caller: ^2.1.1

  # Controle de Estado (opcional)
  provider: ^6.1.2

  # Leitura de notificações (experimentos futuros)
  receive_sharing_intent: ^1.6.4

  # Câmera própria
  camera: ^0.11.1

  # Outras utilidades
  intl: ^0.20.2
  shared_preferences: ^2.2.2

  connectivity_plus: ^7.1.1
  battery_plus: ^7.0.0

  # Alarme real (dispara com app fechado)
  alarm: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Elvira.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/personagens/elvira/
    - assets/images/personagens/nelson/
    - assets/images/personagens/paulo/
    - assets/images/vida_real/
    - assets/images/backgrounds/
    - assets/fonts/
    - assets/fonts/numbers/
    - assets/icons/
    - assets/sounds/

#  fonts:
#    - family: Sora
#      fonts:
#        - asset: assets/fonts/Sora-Regular.ttf
#        - asset: assets/fonts/Sora-Bold.ttf
#        - asset: assets/fonts/Sora-SemiBold.ttf
